spring:
  data:
    mongodb:
      host: ${DB:localhost}
      port: 27017
      database: student
  servlet:
    multipart:
      max-file-size: 256MB
      max-request-size: 256MB
      enabled: true
server:
  port: 3500




 # spring.servlet.multipart.max-file-size=256MB
 # spring.servlet.multipart.max-request-size=256MB
 # spring.servlet.multipart.enabled=true
